version: '3.4'

services:
  diogo.softplan.challenge.api1.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"

  diogo.softplan.challenge.api2.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"

